# Problem 2:
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

numbers = [1, 2]

counter = 1
while counter < 9: # Only testing: "will be 3999999"
    fibonaci = sum(numbers)
    print (fibonaci)
    numbers.pop(1) # fail pop does not pop
    numbers.append(fibonaci)
    print (numbers)
    counter = counter + 1
